accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import create_user

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", create_user, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView,
    TaskDetailView,
    TaskListView,
    TaskUpdateView,
    TaskDeleteView,
    TaskNoteUpdate,
)

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
    path("<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("<int:pk>/update/", TaskNoteUpdate.as_view(), name="task_update"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/", include("tasks.urls")),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return str(self.name)

tasks/models.py
from django.db import models
from django.conf import settings
import datetime

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project",
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    assignee = models.ForeignKey(
        USER_MODEL,
        related_name="tasks",
        on_delete=models.SET_NULL,
        null=True,
    )
    notes = models.CharField(max_length=120, null=True)

    def __str__(self):
        return str(self.name)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


# Create your views here.
def create_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from projects.models import Project


# Create your views here.
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = [
        "name",
        "description",
        "members",
    ]

    def get_success_url(self) -> str:
        return reverse_lazy("show_project", args=[self.object.id])

tasks/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task


# Create your views here.
class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = [
        "name",
        "start_date",
        "due_date",
        "notes",
        "project",
        "assignee",
    ]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = "tasks/detail.html"


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/delete.html"
    success_url = reverse_lazy("show_my_tasks")


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")


class TaskNoteUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/update.html"
    fields = ["notes"]
    success_url = reverse_lazy("task_detail")

projects/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Projects and tasks</title>
        <link rel="stylesheet" href="{% static 'css/static.css' %}">
    </head>
    <body class="stars">
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
        {% block chart %}
        {% endblock chart %}
        <footer>
            <div>This website created and designed by Adrian (Bun)</div>
            <div>About Me</div>
        </footer>
    </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="project-form">
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}
    <main>
        <div class="project-detail">
            <h1>{{ project.name }}</h1>
            {{ project.description|markdownify }}
            <h2>Tasks</h2>
            <p class="info-tab">
                Click on each task for notes!
            </p>
            <p>
                <a href="{% url 'create_task' %}">Create a new task</a>
            </p>
            {% if project.tasks.all|length == 0 %}
                <p>
                    This project has no tasks
                </p>
            {% endif %}
            {% if project.tasks.all|length > 0 %}
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>
                    </thead>
                    <tbody>
                        {% for tasks in project.tasks.all %}
                            <tr>
                                <td>
                                    <a class='grow' href="{% url 'task_detail' tasks.pk %}">{{ tasks.name }}</a>
                                </td>
                                <td>{{ tasks.assignee }}</td>
                                <td>{{ tasks.start_date }}</td>
                                <td>{{ tasks.due_date }}</td>
                                {% if tasks.is_completed == False %}
                                <td> 
                                <form method="post" action="{% url 'complete_task' tasks.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form>
                                </td>   
                                {% else %}
                                    <td>{{ tasks.is_completed }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="project-list">
            <h1>My Projects</h1>
            <p>
                <a href="{% url 'create_project' %}">Create a new project</a>
            </p>
            {% if project_list|length == 0 %}
                <p>
                    You are not assigned to any projects
                </p>
            {% else %}
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Number of tasks</th>
                    </thead>
                    <tbody>
                        {% for projects in project_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'show_project' projects.pk %}">{{ projects.name }}</a>
                                </td>
                                <td>{{ projects.tasks.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="task-form">
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/delete.html
{% extends 'base.html' %}
{% block content %}
    <main>
        {% comment %} <div class="task-form"></div> {% endcomment %}
        <form method="post" class="task-detail">
            {% csrf_token %}
            <p>
                Do you really want to delete "{{ task }}"?
            </p>
            {{ form.as_p }}
            <button class="button">Delete</button>
        </form>
    </main>
{% endblock content %}

tasks/templates/tasks/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}
    <main>
        <div class="task-detail">
            <h1>{{ task.name }}</h1>
            {{ task.notes|markdownify }}
            <a href="{% url 'task_delete' task.pk %}">Delete Task?</a>
            |
            <a href="{% url 'task_update' task.pk %}">Update Task Notes?</a>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="my-tasks-list">
            <h1>My Tasks</h1>
            {% if task_list|length == 0 %}
                <p>
                    You have no tasks
                </p>
            {% else %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for assigned in task_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'task_detail' assigned.pk %}">{{ assigned.name }}</a>
                                </td>
                                <td>{{ assigned.start_date }}</td>
                                <td>{{ assigned.due_date }}</td>
                                {% if assigned.is_completed %}
                                    <td>Done</td>
                                {% else %}
                                    <td>
                                        <form method="post" action="{% url 'complete_task' assigned.pk %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="is_completed" value="True">
                                            <button>Complete</button>
                                        </form>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/update.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <div class="task-detail">
            <h1>Update Task Note</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Update!</button>
            </form>
        </div>
    </main>
{% endblock content %}